#!/bin/bash

# Test snapshot functionality

. ./common

for i in 0 1 2; do
    _start_sheep $i
done

_wait_for_sheep 3

_cluster_format -c 1

$QEMU_IMG create sheepdog:test 4G
for i in `seq 1 9`; do
    _qemu_io -c "write 0 512 -P $i" sheepdog:test
    $QEMU_IMG snapshot -c tag$i sheepdog:test
done

_qemu_io -c "read 0 512 -P 9" sheepdog:test
for i in `seq 1 9`; do
    _qemu_io -c "read 0 512 -P $i" sheepdog:test:tag$i
done
