#!/bin/bash

# Test vdi rollback

. ./common

for i in `seq 0 4`; do
    _start_sheep $i
done

_wait_for_sheep 5

_cluster_format
$DOG vdi create test 4G

_qemu_io -c "write 0 512 -P 1" sheepdog:test
$DOG vdi snapshot test -s snap1
_qemu_io -c "write 0 512 -P 2" sheepdog:test

echo yes | $DOG vdi rollback test -s snap1
_qemu_io -c "read 0 512 -P 1" sheepdog:test
$DOG vdi tree | _filter_short_date
_vdi_list

_qemu_io -c "write 0 512 -P 2" sheepdog:test
$DOG vdi snapshot test -s snap2
_qemu_io -c "write 0 512 -P 3" sheepdog:test

echo yes | $DOG vdi rollback test -s snap1
_qemu_io -c "read 0 512 -P 1" sheepdog:test
$DOG vdi tree | _filter_short_date
_vdi_list

echo yes | $DOG vdi rollback test -s snap2
_qemu_io -c "read 0 512 -P 2" sheepdog:test
$DOG vdi tree | _filter_short_date
_vdi_list

echo yes | $DOG vdi rollback test -s snap1
_qemu_io -c "read 0 512 -P 1" sheepdog:test
$DOG vdi tree | _filter_short_date
_vdi_list

_qemu_io -c "write 0 512 -P 3" sheepdog:test
$DOG vdi snapshot test -s snap3
_qemu_io -c "write 0 512 -P 4" sheepdog:test
$DOG vdi snapshot test -s snap4

# these fail since the snap ids don't belong to snapshots
echo yes | $DOG vdi rollback test -s 0
echo yes | $DOG vdi rollback test -s 5

echo yes | $DOG vdi rollback test -s snap3
_qemu_io -c "read 0 512 -P 3" sheepdog:test
$DOG vdi tree | _filter_short_date
_vdi_list
